version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 
services:
  dockerapi:
    image: razom.ui_and_api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=mainFilStorage;username=db_user;password=1db_user1"
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "1db_user1"
      POSTGRES_DB: "mainFilStorage"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - postgres_image

volumes:
  db_volume:
  pgadmin:
         